services:
  backend:
    build: ./sources
    command: uvicorn application.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - db_storage:/var/data
    ports:
      - 8000:8000


volumes:
  db_storage:
