services:
  backend:
    build: ./sources
    command: uvicorn application.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./sources/:/usr/src/application/
    ports:
      - 8000:8000
